# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
version: "3.3"
networks:
  proxy_net:
    external: true

services:
  countryconfig:
    # image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:${COUNTRY_CONFIG_VERSION}
    build: .
    restart: unless-stopped
    ports:
      - '3040:3040'
    environment:
      - AUTH_URL=http://192.168.0.50:4040
      - AUTH_API_URL='http://192.168.0.50:4040/'
    networks:
      - proxy_net
    deploy:
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_net
      - traefik.http.routers.countryconfig.rule=Host(`countryconfig.opencrvs.techno-associates.live`)
      - traefik.http.routers.countryconfig.entrypoints=websecure,web
      - traefik.http.services.countryconfig.loadbalancer.server.port=3040
      - traefik.http.routers.countryconfig.tls.certresolver=myresolver